# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Gravityzone monitoring

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2 
    - name: Use Node.js ${{ matrix.node-version }} 
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    # Make new deirectory if not yet exsists
    - run: mkdir -p /var/www/gravityzone-snmp/prod
    # Move files from runner folder to new folder (exclude files you dont want deleted)
    - run: rsync -rcv --delete . /var/www/gravityzone-snmp/prod --exclude=conf.json --exclude=node_modules
    # Install new packages in working directory
    - run: npm --prefix /var/www/gravityzone-snmp/prod i
    - run: npm --prefix /var/www/gravityzone-snmp/prod run build --if-present
    # Restart service
    - run: sudo systemctl restart gravityzone-snmp
